### ISSUE TITLE
Gold Dust Exchange can not be handed in

### ISSUE THREAD

**Issue by Fabrice-leterme** [The-Alpha-Project/alpha-core#214] opened 2022-01-04 10:57 UTC
You can complete this quest, but you can not hand it in to the quest npc.

If you do, you can no longer use any ingame options.

No talking to npc's, no using quit or logout in menu either.

**Comment by Fabrice-leterme** [comment] 2022-01-04 12:26
This seems to be an issue with the experience received from the quest. I put the xp_rate higher (think it was x3) to speed through the content faster

**Comment by devwar87** [comment] 2022-01-06 02:10
Can't reproduce this. Completed with rate x1 and x3 and got the corresponding reward: [Bag of Marbles]

**Comment by Fabrice-leterme** [comment] 2022-01-06 08:44
I reproduced by putting rate higher, try x10

**Comment by GrenderG** [comment] 2022-01-06 16:15
```
  File "/home/grender/PycharmProjects/alpha-core/game/world/managers/objects/units/player/quest/ActiveQuest.py", line 43, in reward_xp
    self.owner.give_xp([xp], notify=False)
  File "/home/grender/PycharmProjects/alpha-core/game/world/managers/objects/units/player/PlayerManager.py", line 738, in give_xp
    self.set_uint32(PlayerFields.PLAYER_XP, self.xp)
  File "/home/grender/PycharmProjects/alpha-core/game/world/managers/objects/ObjectManager.py", line 233, in set_uint32
    self.update_packet_factory.update(index, value, 'I')
  File "/home/grender/PycharmProjects/alpha-core/network/packet/update/UpdatePacketFactory.py", line 44, in update
    self.update_values[index] = pack(f'<{value_type}', value)
struct.error: argument out of range
```

Seems to be caused by an overflow.

**Comment by GrenderG** [comment] 2022-01-06 17:17
Should be fixed here https://github.com/The-Alpha-Project/alpha-core/commit/1e94f0913d0b4aa6dfa8f5e75afd66bc7534ee1a.

**Closed by GrenderG** 2022-01-06 17:17 UTC
