### ISSUE TITLE
Heals and Buffs attempt to target selected neutral mob both out and in combat

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#257] opened 2022-04-01 10:30 UTC
**Description**
If you have a neutral (yellow) mob selected and try to heal or buff , it tries to target the mob and does nothing at end of cast

**Steps to reproduce**
1. Select neutral mob that is not a critter - Ex: [Mountain Boar](https://classic.wowhead.com/npc=1190/mountain-boar)
2. Cast buff or heal - Ex: [Holy Light](https://classic.wowhead.com/spell=635/holy-light) , Seal of Might (maybe Spell #636 , can't find source)
3. Nothing happens and mana is spent

**Expected behavior**
Have cursor change to select target for cast

**Comment by Fluglow** [comment] 2022-04-01 13:05
Caused by the client considering neutral targets assistable and `EffectTargets` considering valid targets to only be unattackable ones. `target_is_friendly` in `EffectTargets.get_simple_targets` should account for neutral targets too (`target_is_assistable`?), assuming the client's behavior is intended.

**Comment by Daribon** [comment] 2022-06-18 03:18
I cannot reproduce this bug. I was able to target Mountain Boar and buff myself with Frost Armor
Tried with paladin using Holy Light and Seal of Might and I was able to use both when targeting Mountain Boar.

**Comment by OrthoTemplar** [comment] 2022-06-18 10:15
Try with AoE buffs like a Warrior shout or a aura . Also I think the caster in this case is the mob.

**Comment by Fluglow** [comment] 2022-08-10 15:06
Closing since this bug can't be reproduced anymore.

**Closed by Fluglow** 2022-08-10 15:06 UTC
Labels: bug, spell
