### ISSUE TITLE
Bug: "You can't log out because you can't sit down right now"

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#467] opened 2022-08-12 08:48 UTC
**Describe the bug**
Under certain circumstances when you type "/camp" to log out you get the message "You can't log out because you can't sit down right now".

I'm assuming this is a client issue, but it has happened to me twice now.

As you can see from the second screenshot I can in fact sit down.

**Steps to reproduce**
I'm not sure how to reproduce it. 

* In the first case I think I attacked a critter which got stuck in a wall.
* In the second case I think I attacked a mob another player was attacking.

I can't find "You can't log out because you can't sit down right now" in the server code.

**Expected behavior**
I expect to be able to log out.

**Screenshots**

![Cannot log out](https://user-images.githubusercontent.com/110961189/184318889-ef51c36a-205d-4385-9ee2-c5a9968f40f7.jpg)

![Cannot log out2](https://user-images.githubusercontent.com/110961189/184318981-3d2d028a-6366-4735-84ee-b8d6841039fe.jpg)

**Comment by GrenderG** [comment] 2022-08-12 11:27
That's because your character is in combat. I have experienced this issue where you are stuck in combat but I haven't managed to reproduce it. If you found a way to reproduce it please let us know.

**Comment by sadpanda353** [comment] 2022-08-12 14:30
The  famous ''combat bug'' is a pleague that hit private servers since a loooooong time, if you manage to fix this i will consider you as a god lol.

**Comment by GrenderG** [comment] 2022-08-12 14:53
As a temporary solution you can type `bootme` in the console, it will kick you to the character selection screen.

**Comment by Yushe** [comment] 2022-08-12 17:24
This bug seemed to happen to be a lot when I was in a group killing elite orcs, so if you're trying to reproduce it I guess that would be the best way to debug it.
It didn't happen consistently though more just randomly.

**Comment by GrenderG** [comment] 2022-08-20 14:45
We think this issue should be fixed now as we weren't able to reproduce it anymore with some changes we made in [#536](https://github.com/The-Alpha-Project/alpha-core/pull/516) and https://github.com/The-Alpha-Project/alpha-core/commit/f32f33424d14eca77f499daa83e07d3dbc70808a. Closing this until further notice.

**Closed by GrenderG** 2022-08-20 14:45 UTC
Labels: bug

**Comment by heyitsbench** [comment] 2023-04-02 19:33
This happened to me after going AFK outside the Goldshire inn for a couple hours. No idea if it kicked in before that point due to something else I did, but that's when I noticed it. I was completely solo just killing mobs and running around for quests in the area.

**Comment by GrenderG** [comment] 2023-04-02 21:09
Seems like the combat but is still haunting us. 🤔

**Comment by Yushe** [comment] 2023-04-03 06:52
This bug tends to only happen to me when I use random spells or dev spells that aren't entirely supported.
Sometimes attacking and killing a mob can fix it because it resets your combat status, I'd have to test some more.
